services:
  telegram-bot:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - ZOHO_CLIENT_ID=${ZOHO_CLIENT_ID}
      - ZOHO_CLIENT_SECRET=${ZOHO_CLIENT_SECRET}
      - ZOHO_ORGANIZATION_ID=${ZOHO_ORGANIZATION_ID}
      - USER_ROLES=${USER_ROLES}
    volumes:
      - ./zoho_tokens.json:/app/zoho_tokens.json
      - ./src:/app/src
      - ./credentials.json:/app/credentials.json
      #   - /mnt/hdd:/app/downloads
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: >
      sh -c "touch /app/zoho_tokens.json && python -u /app/src/main.py"
