services:
  telegram-bot:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - ZOHO_CLIENT_ID=${ZOHO_CLIENT_ID}
      - ZOHO_CLIENT_SECRET=${ZOHO_CLIENT_SECRET}
    # volumes:
    #   - /mnt/hdd:/app/downloads
    volumes:
    - ./zoho_tokens.json:/app/zoho_tokens.json
    restart: unless-stopped
    command: >
      sh -c "touch /app/zoho_tokens.json && python -u src/main.py"